# Generated by Django 2.1.1 on 2018-09-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=3000)),
                ('hitpoints', models.IntegerField(default=1)),
                ('cost', models.IntegerField(default=1)),
                ('deploy_time', models.FloatField(default=0.0)),
                ('damage', models.IntegerField(default=1)),
            ],
        ),
    ]
