# Generated by Django 2.1.1 on 2018-09-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardcreation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='card',
            table='card',
        ),
    ]
